import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ReactSearchAutocomplete } from 'react-search-autocomplete'
import Link from 'next/link'
import { useRouter } from 'next/router'
import axios from 'axios'
import { useEffect } from 'react'

const Home: NextPage = () => {
  const router = useRouter();

  useEffect(()=> {
  },[])

  const items = [
    {
      id: 0,
      name: 'Cobol'
    },
    {
      id: 1,
      name: 'JavaScript'
    },
    {
      id: 2,
      name: 'Basic'
    },
    {
      id: 3,
      name: 'PHP'
    },
    {
      id: 4,
      name: 'Java'
    }
  ]

  const handleOnSearch = (string:any, results:any) => {}

  const handleOnHover = (result:any) => {}

  const handleOnSelect = (item:any) => {
    router.push("/" + item.id)
  }

  const handleOnFocus = () => {
    console.log('Focused')
  }

  const formatResult = (item:any) => {
    return (
      <>
      <Link href={"/"+item.id}>
        <div style={{ display: 'block', textAlign: 'left', cursor:"pointer" }}>name: {item.name}</div>
      </Link>
      </>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Mobile PV</a>
        </h1>

        <p className={styles.description}>
          Type your username on the following search bar
        </p>

        <div style={{width:"60%"}}>
          <ReactSearchAutocomplete
              items={items}
              onSearch={handleOnSearch}
              onHover={handleOnHover}
              onSelect={handleOnSelect}
              onFocus={handleOnFocus}
              autoFocus
              formatResult={formatResult}
            />
        </div>

      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          LTF2 Mobile PV Group
        </a>
      </footer>
    </div>
  )
}

export default Home
